### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mahxxd** [Khanmanan/automod-bot#27]
internal/modules/cjs/loader.js:613
2:43 PM
    throw err;
2:43 PM
    ^
2:43 PM
2:43 PM
Error: Cannot find module '/app/server.js'
2:43 PM
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
2:43 PM
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
2:43 PM
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
2:43 PM
    at internal/main/run_main_module.js:17:11

**Comment by VIGHNESH-Y** [comment]
Please send me the Image of your Consoles Error.
