### ISSUE TITLE
Self Host

### ISSUE THREAD

**Issue by zarigata** [Khanmanan/automod-bot#29]
is there a way to self host the bot? in a micro server on in a Raspberry?

**Comment by VIGHNESH-Y** [comment]
Yes if you know how to use pm2

**Comment by zarigata** [comment]
how would i start with pm2? not quite a good at node.js

**Comment by zarigata** [comment]
also i allways fint he error with canvas sempai with the local one 
- /home/pi/automod-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pi/automod-bot/index.js:8:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/automod-bot/index.js' ]
}

**Comment by VIGHNESH-Y** [comment]
Install the module pm2 install <module-name>
