### ISSUE TITLE
cant start the bot

### ISSUE THREAD

**Issue by maybefads** [Khanmanan/automod-bot#39]
TypeError: Node option "host" must be present and be a non-empty string.
    at check (home\node_modules\erela.js\dist\structures\Node.js:25:15)
    at new Node (home\node_modules\erela.js\dist\structures\Node.js:68:9)        
    at new Manager (home\node_modules\erela.js\dist\structures\Manager.js:82:17) 
    at new MusicManager (home\src\structures\MusicManager.js:29:5)
    at new BotClient (home\src\structures\BotClient.js:64:25)
    at Object.<anonymous> (home\bot.js:11:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
    
    
    
    
 please help, i can't understand a thing :(

**Comment by DesignAny** [comment]
the same

**Comment by MrrVit665** [comment]
Add your lavalink

**Comment by JKane22** [comment]
With my PR, this should be fixed but will not allow users to listen to music until you have filled out the `/automod-bot/config.json`.

Simple Fix: 
Fill out the Config.json file
