### ISSUE TITLE
Cant start the bot 

### ISSUE THREAD

**Issue by ultra-beep** [Khanmanan/automod-bot#42]
hey @Khanmanan @MojitoTea @ZeroDiscord @NotKaskus i would like to start up the bot but i get this error
> discord-js-bot@4.1.0 start
> nodemon bot.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node bot.js`
C:\Users\proki\Downloads\automod-bot-main\node_modules\erela.js\dist\structures\Node.js:25
        throw new TypeError('Node option "host" must be present and be a non-empty string.');
        ^

TypeError: Node option "host" must be present and be a non-empty string.
    at check (C:\Users\proki\Downloads\automod-bot-main\node_modules\erela.js\dist\structures\Node.js:25:15)
    at new Node (C:\Users\proki\Downloads\automod-bot-main\node_modules\erela.js\dist\structures\Node.js:68:9)
    at new Manager (C:\Users\proki\Downloads\automod-bot-main\node_modules\erela.js\dist\structures\Manager.js:82:17)
    at new MusicManager (C:\Users\proki\Downloads\automod-bot-main\src\structures\MusicManager.js:29:5)
    at new BotClient (C:\Users\proki\Downloads\automod-bot-main\src\structures\BotClient.js:64:25)
    at Object.<anonymous> (C:\Users\proki\Downloads\automod-bot-main\bot.js:11:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
[nodemon] app crashed - waiting for file changes before starting...
 could you help me

**Comment by JKane22** [comment]
Hey! I'm going to give a stab at this error you are having right now. 

I am seeing the same error on my end and I am looking into it right now...

**Comment by JKane22** [comment]
Hello, This issue is fixed and no more errors for:
`TypeError: Node option "host" must be present and be a non-empty string.`

I did add a way for the bot to start without the host music array in the config being filled out. 

I would like to note that music will not work without `/automod-bot/config.json` being fill out with the proper information. 

This is what the Music tab should look like in `/automod-bot/config.json`

![](https://i.imgur.com/Qjn6jWj.png)

### Fix: 
Within the MusicManager.js file there was a line of code looking like this:
`Line: 30 | nodes: MUSIC.NODES.HOST`

I have changed that to look a little like this:
`Line: 30 | nodes: MUSIC.NODES.HOST ? MUSIC.NODES.HOST : [], `

*I did also add a Logger if you don't have anything in there it should log that info to the console.*

**Comment by ultra-beep** [comment]
Thank you for this

**Comment by ultra-beep** [comment]
and how do i make it so i can play music

**Comment by ultra-beep** [comment]
I filled it out but it says it doesnt have nodes

**Comment by ultra-beep** [comment]
maybe i putted it wrong but what do you need to put with the host and identifier

**Comment by ultra-beep** [comment]
O ok thx for the help and to fix the bug

Op wo 13 jul. 2022 21:53 schreef Jeremiah Kane ***@***.***>:
