### ISSUE TITLE
lava link errors | help cmd error

### ISSUE THREAD

**Issue by jacobharr24** [Khanmanan/automod-bot#85]
Error
Error: connect ECONNREFUSED 192.46.210.230:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Message
connect ECONNREFUSED 192.46.210.230:443
Error
Error: connect ECONNREFUSED 192.46.210.230:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Message
connect ECONNREFUSED 192.46.210.230:443
Error
Error: connect ECONNREFUSED 192.46.210.230:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Message
connect ECONNREFUSED 192.46.210.230:443
Error
Error: connect ECONNREFUSED 192.46.210.230:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Message
connect ECONNREFUSED 192.46.210.230:443
Error
Error: connect ECONNREFUSED 192.46.210.230:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Message
connect ECONNREFUSED 192.46.210.230:443
Error
Error: Unable to connect after 5 attempts.
    at Timeout._onTimeout (C:\Users\Administrator\automod-bot\node_modules\erela.js\dist\structures\Node.js:176:31)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
Message
Unable to connect after 5 attempts.

**Comment by jacobharr24** [comment]
ADDITINAL ERRORR:

TypeError
TypeError: Cannot read properties of null (reading 'id')
    at C:\Users\Administrator\automod-bot\dashboard\routes\discord.js:12:25
    at Layer.handle [as handle_request] (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:323:13)
    at C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:341:12)
    at next (C:\Users\Administrator\automod-bot\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\Administrator\automod-bot\dashboard\app.js:36:7
Message
Cannot read properties of null (reading 'id')

**Comment by jacobharr24** [comment]
help cmd error: 
DiscordAPIError
DiscordAPIError: Invalid Form Body
components[1].components[3].url: Scheme "806603922571395133" is not supported. Scheme must be one of ('http', 'https', 'discord').
    at RequestHandler.execute (C:\Users\Administrator\automod-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (C:\Users\Administrator\automod-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async TextChannel.send (C:\Users\Administrator\automod-bot\node_modules\discord.js\src\structures\interfaces\TextBasedChannel.js:175:15)
    at async HelpCommand.messageRun (C:\Users\Administrator\automod-bot\src\commands\utility\help.js:56:23)
    at async HelpCommand.executeCommand (C:\Users\Administrator\automod-bot\src\structures\Command.js:160:7)
Message
Invalid Form Body
components[1].components[3].url: Scheme "806603922571395133" is not supported. Scheme must be one of ('http', 'https', 'discord').

**Comment by jacobharr24** [comment]
any solutions?
